### ISSUE TITLE
Renderman conflict or issue, crash occurs in Houdini if subnet is modifed while rendering

### ISSUE THREAD

**Issue by mswindler** [byu-animation/dccpipe#117]
From Dallin
I just tried it again.  It works fine when I just rendered it and published, but when I add a material, render it, and then publish, it crashes.

Hmm.  I just tried it again and if I stop the render before I publish, it seems to work.  That may be a workaround for now.

Also I noticed that when you check out an object, it sets the default material to ../material_network/shop_material_network/vopmaterial1

Could we change it to ../material_network/material_network/surface instead?

**Comment by mswindler** [comment]
https://rmanwiki.pixar.com/display/RFH22/RenderMan+for+Houdini+22.5
This states: 
Known Issues
 - Rewiring subnet indirect inputs

Maybe this means that if the material is contained within a subnet on the same node, this is an issue?

**Comment by mswindler** [comment]
Fixed the issue with crash during publish. Added correct material reference.

Still crashing during render when nodes are rewired.

**Comment by mswindler** [comment]
Find a workaround for this

**Comment by semagnum** [comment]
Should we consider this closed since we're switching to Mantra?
