### ISSUE TITLE
Maya crashing for animators

### ISSUE THREAD

**Issue by mswindler** [byu-animation/dccpipe#130]
Dallin told me this, need to find more information and steps to replicate.

**Comment by mswindler** [comment]
https://knowledge.autodesk.com/support/maya/troubleshooting/caas/sfdcarticles/sfdcarticles/Constant-crashing-with-Maya-2017.html

**Comment by semagnum** [comment]
I couldn't replicate the issue on my machine.  One thing I noticed is that upon loading the file, Maya warned that its playback cache was near-full.  When I disabled some preferences on playback, it got more jumpy especially.
It could simply be a memory issue, especially if animators have their Undo limit set to "unlimited."  We'll check if that's the case for those who have it crash.

**Comment by semagnum** [comment]
Logging a time the issue appeared:
- Shot D007
- after working on it for 30 minutes (saving about every 5 minutes), the animator tumbled the viewport and selected the salt geometry in the boats when it crashed
- the "crash" was more like Maya froze for so long that force quitting was necessary
- her undo queue is set to 50

**Comment by htinney** [comment]
What version of Maya are you guys using now? If it's 2019, I'd look into debugging the Evaluation Manager because "playback" seems to indicate thst Cached Playback might be the problem: https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/Maya-Customizing/files/GUID-3CB35662-DB1D-4CF3-9135-E09B973635DE-htm.html

You can read more about the technical nature of cached playback here:
http://download.autodesk.com/us/company/files/MayaCachedPlayback/2019/MayaCachedPlaybackWhitePaper.html

**Comment by htinney** [comment]
I bring it up because we have to debug cached playback at Blue Sky all the time, because it's a relatively new feature that isn't prefectly stable

**Comment by semagnum** [comment]
@htinney , yes it is with Maya 2019.  The occurrences all seem to be related to playback or editing the animation.

**Comment by mswindler** [comment]
I talked to Hana and she said they've known about the playback cache issue, and they've had it turned off for the past couple months, @htinney do you know if it could still be causing problems if it's turned off?

**Comment by htinney** [comment]
No, but being unable to reproduce on a different user would indicate that it might be a user preference. Try nuking prefs. Also, if you are working within an open session of Maya where cached playback was turned on at some point, once you turn it off you might still need to flush the cache to free up memory.

**Comment by semagnum** [comment]
Looks like a preference reset is working for the animators.  I told them to slowly change preferences back and see when it starts crashing again.

**Comment by semagnum** [comment]
@htinney , after they've changed preferences, it seemed to not crash for a while, but Maya started running much slower until it eventually has been crashing again.  The only preferences they changed were related to the curve editor window, not graphics related.  Can you think of anything else we could look into?

**Comment by mswindler** [comment]
Final solution (found in November):
In Preferences > Settings > Animation > Evaluation change Evaluation mode from DG to Serial or Parallel.

No crashes since. 

Also not a DCCPipe issue, so closing.
