### ISSUE TITLE
Alembic export not succeeding even with top level group tagged

### ISSUE THREAD

**Issue by squidbidness** [byu-animation/dccpipe#146]
With the shot asset 'test-tentacle-sim' in the Stowaway pipeline, I select the top level group 'Tentacle_GRP', then I click the shelf tool 'tag', and confirm.  I then click to export, (with 'alembic' implicitly selected), and get an error dialog that says "No alembics were exported. Make sure the top-level group is tagged".
If I then attempt to clone the shot in Houdini, the node network is empty except for an empty group box.

**Comment by mswindler** [comment]
So tagging for shots works differently from tagging sets. 

I can explain how you'll want to tag items in shots if you come into the lab, but the basic idea is you need to tag the top-level node for each asset that is referenced into the shot.
