### ISSUE TITLE
Fix dcc HDAs

### ISSUE THREAD

**Issue by mswindler** [byu-animation/dccpipe#48]
Some HDAs have reload buttons or other button parameters that are not working when pressed.

i.e. DCC Geo.

Fix the scripts within these HDAs.

**Comment by nwh19** [comment]
dcc_set still has a bug in "rebuild" button. smart rebuild is creating duplicates of assets. This will need to be resolved.

**Comment by mswindler** [comment]
Last thing to do is fix smart rebuild to only rebuild assets that have been changed. This may be fairly complex however, so just going to set default mode to "clean" for now

**Comment by mswindler** [comment]
Not gonna worry about this as it's working fine as is.
