### ISSUE TITLE
Add option to save current changes to asset when choosing a new asset to clone

### ISSUE THREAD

**Issue by mswindler** [byu-animation/dccpipe#7]
When cloning an asset, the changes to the current asset are saved over the scene file of the commit user was working on previously

We should give user an option to save their changes to the asset or not when they opt to clone another asset, and if so, save as a new publish.

https://github.com/byu-animation/dccpipe/blob/master/pipe/tools/mayatools/cloners/cloner.py

**Comment by nwh19** [comment]
Instead of saving over, create a new publish
