### ISSUE TITLE
Add comment dialog for Houdini publish

### ISSUE THREAD

**Issue by mswindler** [byu-animation/dccpipe#83]

**Comment by mswindler** [comment]
@semagnum it looks like there will still need to be some changes to your commit:
https://github.com/byu-animation/dccpipe/commit/6b35b4ee7d9b05ee2113c92cc855e46eef08e3b1

1. qd.input() is great for Maya, but in Houdini shows black text on a black bar. We can't style QInputDialogs, so that's what the HoudiniInput class is for (in pipe/gui/quick_dialogs). See 28-32 here: https://github.com/byu-animation/dccpipe/blob/9b8682a6cd846fd4a790a9a22aefb377fd609314/pipe/tools/houtools/creator/creator.py#L28
2. There are 3 places where we'll need to request comment input from the user:
publish_content_hda()
shot_results()
publish_hda()

If you have questions on this, I'm more than happy to help!

**Comment by semagnum** [comment]
https://github.com/byu-animation/dccpipe/commit/d6c13c869f3028714aea65524c39751b4e05a040
