### ISSUE TITLE
Don't import any gui modules until the functions are called

### ISSUE THREAD

**Issue by mswindler** [byu-animation/dccpipe#91]
In https://github.com/byu-animation/dccpipe/blob/master/pipe/am/pipeline_io.py

Remove line 7

Insert it inside functions:
set_permissions()
checkFileName()

(as the first line of the function)

The error 
`ImportError: /lib64/libQt5Core.so.5: version `Qt_5.12' not found (required by /users/animation/swind6/Desktop/spencerPipe/dccpipe/.venv/lib/python2.7/site-packages/PySide2/libpyside2-python2.7.so.5.12)`
Is occurring because Qt isn't set up to work outside of the DCC applications that we are using. This module can be safely imported once the programs are running, but not on project initialization.

That's why we can put the imports inside the functions rather than at the top of the file.

**Comment by semagnum** [comment]
The problem has been fixed and pushed to the master branch.
