### ISSUE TITLE
Finish functions for Substance tools

### ISSUE THREAD

**Issue by mswindler** [byu-animation/dccpipe#94]
file:///opt/Allegorithmic/Substance_Painter/resources/javascript-doc/alg.html

**Comment by mswindler** [comment]
https://doc.qt.io/qt-5/qmltypes.html

**Comment by nwh19** [comment]
I added a commit here but accidentally forgot to put a space before the issue number. The commit is 8d3fd77 with the commit message:

**fix: bugs in exporting fbx when creating and publishing#94**

**Comment by mswindler** [comment]
Awesome! Do you want to add logic so the fbxexport only goes when the asset is a prop or actor?

**Comment by nwh19** [comment]
Sure thing!

**Comment by mswindler** [comment]
@nwh19 I added icons for the substance shelf:

load.png
save.png
export.png
import.png

**Comment by nwh19** [comment]
There are still enhancements to make, but the essentials are completed.
