### ISSUE TITLE
Auto Scale Assets when cloned in Houdini

### ISSUE THREAD

**Issue by scearnest** [byu-animation/dccpipe#98]
The assets brought in right now are very large at default and need to be scaled by a factor of 10 or so from Maya. It would be nice to have a default null or transform node in the asset that scales it down.

**Comment by mswindler** [comment]
This can be done fairly easily already, best would be to make a change to DCC Geo for now.

Later, it would be best to have a project setting that determines the scale to use when importing to Houdini.

**Comment by mswindler** [comment]
Waiting for #48 to be finished so we can avoid merge conflicts with binary HDAs that can't be merged.

**Comment by mswindler** [comment]
We need to decide what's best, if they're scaled on the object level or the set level.

**Comment by mswindler** [comment]
Talked to Alicia and Judy. Due to camera issues, we may not move forward with auto-scale in Houdini.

**Comment by mswindler** [comment]
Not going to continue with this after all.
